name: Deploy to VPS

on:
  push:
    branches:
      - vps-izanagi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/projectpabw  
            git checkout vps-izanagi
            git pull origin vps-izanagi
            docker compose up -d --build
